[package]
name = "thetawave-camera"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true, features = [
    "multi_threaded",
    "async_executor",
] }

[features]
dynamic_linking = ["bevy/dynamic_linking"]
