[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
    # Clippy configuration to disable type complexity warnings
    "-A", "clippy::type_complexity",
    "-A", "clippy::enum_variant_names",
    "-A", "clippy::too_many_arguments"
]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustflags = [
    # Enable getrandom backend for WASM
    "--cfg", 'getrandom_backend="wasm_js"',
    # Clippy configuration to disable type complexity warnings
    "-A", "clippy::type_complexity",
    "-A", "clippy::enum_variant_names",
    "-A", "clippy::too_many_arguments"
]
