[package]
name = "thetawave-states"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true, features = [
    "bevy_state",
] }

[features]
dynamic_linking = ["bevy/dynamic_linking"]
