[build]
public_url = "./"
no_default_features = true
features = ["debug"]
release = true

[serve]
port = 8080

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "cp -r assets $TRUNK_STAGING_DIR"]
